name: Publish to VS Code Marketplace
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Run Dagger Pipelines
        run: fluentci run . publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      - name: Upload release assets
        run: fluentci run github_pipeline release_upload
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE: /app/vscode-fluentci-${{ env.RELEASE_VERSION }}.vsix
